version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: saas-login-db
    environment:
      POSTGRES_USER: saas_user
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: saas_login
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saas_user -d saas_login"]
      interval: 5s
      timeout: 5s
      retries: 5

  # pgAdmin (optional, for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
