services:
  # Backend API Service
  - type: web
    name: conecta-api-staging
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/health
    envVars:
      - key: ENVIRONMENT
        value: staging
      - key: PROJECT_NAME
        value: Conecta API (Staging)
      - key: DATABASE_URL
        fromDatabase:
          name: conecta-staging-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 11520 # 8 days
      - key: DEFAULT_LANGUAGE
        value: pt-BR
      - key: SMTP_TLS
        value: true
      - key: SMTP_PORT
        value: 587
      - key: SMTP_HOST
        sync: false # Você precisará configurar isso manualmente
      - key: SMTP_USER
        sync: false # Você precisará configurar isso manualmente
      - key: SMTP_PASSWORD
        sync: false # Você precisará configurar isso manualmente
      - key: EMAILS_FROM_EMAIL
        sync: false # Você precisará configurar isso manualmente
      - key: EMAILS_FROM_NAME
        value: Conecta (Staging)
    autoDeploy: true
    domains:
      - conecta-staging-api.onrender.com

databases:
  - name: conecta-staging-db
    region: oregon
    plan: starter
