name: Conecta CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black mypy flake8
        
    - name: Check code formatting with Black
      run: |
        black --check .
        
    - name: Lint with flake8
      run: |
        flake8 . --count --max-line-length=88 --statistics
        
    - name: Type checking with mypy
      run: |
        mypy .
        
    - name: Run tests with pytest and coverage
      env:
        DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        TEST_EMAIL_USER: ${{ secrets.TEST_EMAIL_USER }}
        TEST_EMAIL_PASSWORD: ${{ secrets.TEST_EMAIL_PASSWORD }}
        SMTP_SERVER: "smtp.gmail.com"
        SMTP_PORT: "465"
        SMTP_TLS: "True"
        SECRET_KEY: "test-secret-key-for-jwt-generation"
        ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      run: |
        pytest --cov=app --cov-report=xml -v
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
    
    - name: Deploy to Railway Staging
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway up --service conecta-staging -d

  deploy-production:
    needs: [test, deploy-staging]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
      url: ${{ vars.RAILWAY_PRODUCTION_URL }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
    
    - name: Deploy to Railway Production
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway up --service conecta-production -d
